### PR TITLE
Api endpoints

### LINKED ISSUE #325: API endpoints
Cljsjs could use richer API to pull out the list of all packages in the group.

/:group-id.json
- List all projects
- Latest version, homepage, clojars url, description
- Download counts?

/:group-id/:artifact-id.json
- Latest version, homepage, clojars url, description
- List of the recent versions
- Download counts?

This is a duplicate to #169 but I thought it best to create a new issue

### PR DESCRIPTION
**Pull request by Deraen**
Fixes #325 

Adds two new endpoints under /api context.

The endpoints display all the columns from db. Perhaps some fields are unnecessary and we should select which fields are included?

- id  unnecessary
- created, promoted_at?

/api/:group-id:
```
[  
   {  
      "description":"an asynchronous web server",
      "downloads":0,
      "homepage":null,
      "scm":null,
      "created":1286468191604,
      "jar_name":"aleph",
      "group_name":"aleph",
      "id":4287,
      "version":"0.1.1-SNAPSHOT",
      "authors":"",
      "user":"ztellman",
      "promoted_at":null
   },
   {  
      "description":"The core data structures for Aleph.",
      "downloads":0,
      "homepage":null,
      "scm":null,
      "created":1285097390088,
      "jar_name":"core",
      "group_name":"aleph",
      "id":3985,
      "version":"0.6.0-SNAPSHOT",
      "authors":"",
      "user":"ztellman",
      "promoted_at":null
   }
]
```

/api/:group-id/:artifact-id
```
{  
   "description":"an asynchronous web server",
   "homepage":null,
   "scm":null,
   "created":1286468191604,
   "jar_name":"aleph",
   "group_name":"aleph",
   "id":4287,
   "recent_versions":[  
      {  
         "downloads":0,
         "version":"0.1.1-SNAPSHOT"
      },
      {  
         "downloads":0,
         "version":"0.1.0-SNAPSHOT"
      }
   ],
   "downloads":0,
   "version":"0.1.1-SNAPSHOT",
   "authors":"",
   "user":"ztellman",
   "promoted_at":null
}
```

### CODE REVIEW

**Comment by dotemacs** [comment]
I've got the same question that I've posted in #325:

* what is the reason for adding the recent versions of the clojar? Wouldn't the user be able to figure this out for her/himself as they would already be looking up a given clojar?

Otherwise: I think that this is really cool that you've added this. :smile:

**Comment by Deraen** [comment]
I don't have any real reasons. I just decided to start by including pretty much everything which is shown on html pages.

Are there reasons to not share the recent versions? It might have a small performance cost but I don't think it should be a problem.

**Comment by dotemacs** [comment]
Hello @Deraen 

sorry for the late reply.

I was just curious as to why this might be required. But since this all the stuff thats already being rendered in the views... no issues here.

Just to set @tobias' mind at ease, about the [question he raised on Twitter](https://twitter.com/tcrawley/status/589565314574123009), and to keep everybody else in the loop:

this change won't affect the change required for the shields.io PR #315.

**Comment by tobias** [comment]
@Deraen thanks for this!

I have some feedback, all of which is open to discussion.

I agree that the `id` and timestamp fields don't need to be exposed,
and I'd like to have a couple of fields named differently. I also
think we should have two "latest" version fields - one for the latest
version (SNAPSHOT or not), and one for the latest release (!SNAPSHOT).

Something like this:

```
// /api/:group-id.json

[
    {
        "description":"an asynchronous web server",
        "downloads":0,
        "homepage":null,
        "scm":null,
        "artifact_name":"aleph",
        "group_name":"aleph",
        // the following two could be the same if there are no newer snapshots
        "latest_version":"0.1.1-SNAPSHOT",
        "latest_release":"0.1.0",
        "authors":"",
        "user":"ztellman"
    },
    { ...
    }
]

// /api/:group-id/:artifact-id.json

{
    "description":"an asynchronous web server",
    "homepage":null,
    "scm":null,
    "artifact_name":"aleph",
    "group_name":"aleph",
    "latest_version":"0.1.1-SNAPSHOT",
    "latest_release":"0.1.0",
    "recent_versions":[
        {
            "downloads":0,
            "version":"0.1.1-SNAPSHOT"
        },
        {
            "downloads":0,
            "version":"0.1.0"
        }
    ],
    "downloads":0,
    "authors":"",
    "user":"ztellman"
}
```

I'd also like to support both json and edn as response types, with the
appropriate content-type header set, and with dashed keyword keys in
the edn (so `:group-name` for edn, `"group_name"` for json).

The current url structure requires repeating the artifact name as the
group name for artifacts where they are the same, which isn't required
when specifying the coordinates for the project in lein/boot (but is
required by maven). Could this be confusing to some users? The show
routes on the web ui are explicit (`/groups/aleph/` is the group page,
`/aleph` and `/aleph/aleph` both give you the artifact). I think the
user needs to/probably already does know that `aleph` is really
`aleph/aleph`, but I wanted to bring it up before we set the url in
stone, just in case someone has a strong preference.

Is there value in including the user in responses? If we do, I think
we should also include an endpoint for retrieving user information
(which would just be a list of groups currently), and we should
include a list of users on the group page. And this feeds back in to
the url discussion from the previous paragraph - if we do expose
users, we need to namespace the urls (`/api/users/`, `/api/groups/`,
`/api/artifacts/`?).

To get the download stats, this has to use `clojars.stats/all`, which
loads `all.edn` (currently a 1.1Mb file) on every call. `all.edn` is
updated once a day, so we could certainly memoize that data with a
ttl.

The majority of the requests to clojars.org are artifact downloads,
which are all static and handled by nginx. Once we expose an api, that
will increase the load on the app itself if it gets used. I don't
think there's anything we need to do about it now, I'm just noting
that committing to an api may lead to further perf/caching work down
the road.

Once we finalize all this, we'll need to document it on the wiki.

**Comment by Deraen** [comment]
What is your thought on how users would select the response format? Indead of file extension on URL I think proper Accept-header parsing would be the way. [ring-middleware-format] could do that. 

Exposing the users and namespacing the urls sounds good to me. When we use urls with namespace we could easily have /artifacts/:artifactId and /artifacts/:groupId/:artifactId

And about the documentation: what are your thoughts of having a automatically generated usable documentation using Swagger? [demo](http://petstore.swagger.io/). This would be very easy to implement using [compojure-api](https://github.com/metosin/compojure-api) but it would require few new dependencies (compojure-api, ring-swagger, Prismatic Schema) and updating several of existing deps (compojure, ring).

**Comment by tobias** [comment]
I personally prefer using a file extension, since it easier to use when doing manual requests, but could be persuaded to require an Accept header instead if there are compelling advantages to doing so. We already use extensions (.json|.svg) for the latest-version endpoint, so it might be nice to stay consistent with that.

I see you've already namespaced the routes and added a `/users` route - that looks good to me.

Swagger looks interesting, but this API is so small, I'd rather document it on the wiki. I'd prefer to not bring in more dependencies, or upgrade the deps we have for so small a benefit.

**Comment by dotemacs** [comment]
Please see this presentation:

https://speakerdeck.com/sferik/content-negotiation-for-rest-apis

Especially paying attention to the third slide from the end, quoting Fielding.

It addresses some of the points raised in this discussion & it would be worth reconsidering.

Thanks

**Comment by Deraen** [comment]
As API routes will be separated under `/api`-prefix I think we can be non-consistent with existing routes (latest-version.json/svg). I think the accept header is the proper way to select the response format.

I added a commit which adds support for selecting output format using accept headers. It's using [ring-middleware-format](https://github.com/ngrunwald/ring-middleware-format). I had to update several dependecies:
- Ring-middleware-format requires updated Ring
- To update Ring we need to update Compojure
  - Compojure (clout) no longer decodes urls
  (weavejester/clout@13c6a93)
  and this causes few tests to fail
- New ring requires clj-time >0.6.0
- Friend is depending on old core.cache

Broken tests are caused by [an endpoint](https://github.com/ato/clojars-web/blob/master/src/clojars/routes/repo.clj#L119-L123) which presumes that slashes are decoded on the url.

E.g. request to url `/group/artifact/1.0.0/..%2F..%2F..%2F..%2F/test.jar` was previously decoded as `/group/artifact/1.0.0/../../../..//test.jar` which wouldn't match the route (I think). Now that slashes are not decoded the request matches the route and hits version validation which throws an exception which is printed  to console and the response has different status code than before.

**Comment by dotemacs** [comment]
Hi @tobias & @Deraen 

I posted the link to the presentation last week, while I was traveling because of this quote by [Roy Fielding](http://en.wikipedia.org/wiki/Roy_Fielding):

    REST is software design on the scale of decades: every detail is 
    intended to promote software longevity and independent evolution. 
    Many of the constraints are directly opposed to short-term efficiency. 
    Unfortunately, people are fairly good at short-term design, and usually 
    awful at long-term design. Most don’t think they need to design past 
    the current release.

I feel that the change @Deraen is proposing make sense. And the fact that we've got **latest-version.json/svg** end points, shouldn't enforce the standard to follow. If anything, maybe there should be a change to redirect, with 301 status code, to the appropriate **/api** endpoint.

**Comment by Deraen** [comment]
Latest-version.svg is a special case as it's used for version badge and accept header can't be used for that.

**Comment by tobias** [comment]
I agree, I think the Accept header makes sense (thanks for making the case for it @dotemacs), and that we should leave the existing latest-version route as is. I'm traveling this week, but will try to review the PR soon. Thanks for the hard work @Deraen!

**Comment by tobias** [comment]
I've merged this in to a branch (https://github.com/ato/clojars-web/commits/api-endpoints) and added the following:

* middleware to block repo PUTs containing `..` since with a newer compojure they will match the repo routes
* memoized `stats/all` with a ttl of 1 hour since it is an expensive call
* added a skeleton for api tests in `clojars.test.integration.api`

@Deraen - can you rebase from that branch, add some tests to confirm api behavior, and add support for `:edn` as a format? With those changes, I think we'll be ready to release.

**Comment by Deraen** [comment]
Tests added and edn format added.

**Comment by tobias** [comment]
Thanks! This is now live: https://clojars.org/api/groups/org.immutant

I'd like to wait a bit to announce it, after you make sure it meets your needs, and after we document it at https://github.com/ato/clojars-web/wiki/Data

**Pull request merged**
