### PR TITLE
Use clj-pgp to verify signature of files

### PR DESCRIPTION
**Pull request by Deraen**
Clj-pgp requires Clojure 1.6.0 so I updated the dependency. Tests pass still so hopefully this didn't cause regressions.

This fixes at least the problem I've been having: #246 
Probably this will also fix bugs: #244, #271, #204, and #134

I tested this locally by creating two users. I first pushed a artifact with user1 thus creating a group. I then added user2 to the group and pushed another version of the artifact with credentials of user2 (and different pgp key). With this fix the user2 is able to promote the artifact.
I checked that if I removed pubkey from user2's profile, the promote is not available etc.

### CODE REVIEW

**Comment by Deraen** [comment]
Note: clj-pgp depends on newer version of bountycastles library. But as we have direct dependency on it we are using the older version. Seems to work still.

**Comment by martinklepsch** [comment]
:+1:

**Comment by martinklepsch** [comment]
@xeqi is there anything that could/should be done to get this merged?

**Comment by ikitommi** [comment]
would love to see this merged.

**Comment by Deraen** [comment]
Fixes #291 also

**Comment by ato** [comment]
Thanks. Now live in production as 0.15.11.

**Pull request merged**
